### ISSUE TITLE
tacit-colors.css

### ISSUE THREAD

**Issue by yegor256** [yegor256/tacit#198]
How about we add a new CSS to this framework. It will contain properly defined colors, instead of default HTML ones, which are ugly. Something like this:

```css
.red {
  color: '#FB3640': 
}
.blue {
  color: '#1F487E';
}
```

Later, it will be easy to just do:

```
<p class="red">Hello, world!</p>
```

We should find a good looking palette somewhere and use/copy it.
