### ISSUE TITLE
Duplicate body declarations in the output

### ISSUE THREAD

**Issue by tmpfs** [yegor256/tacit#210]
Just playing around with Tacit and I notice that certain styles are repeated in the generated output.

I downloaded the min.css version (current version linked in the README) and unminified it and see:

```css
input,
textarea,
select,
button,
option,
html,
body {
    font-family: system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 18px;
    font-stretch: normal;
    font-style: normal;
    font-weight: 400;
    line-height: 29.7px;
}
```

Repeated several times. I looked at the min.css file to check if the problem is with the unminifier and the duplications appear to exist there.

I am going to fix it manually for what I need to do, this is just to let you know you should check the SASS compiler output, something appears to be amiss.
